### PR TITLE
Implement docstrings for UDL

### PR DESCRIPTION
**Pull request by arg0d**
Docstrings are declared in .udl file by prefixing a line with three slashes ///. Docstrings can be placed basically anywhere - functions, objects, methods, constructors, callbacks, etc.. A docstring placed in a wrong place will generate UDL parser error.

### CODE REVIEW

**Comment by arg0d** [comment]
This PR was created for `new-upstream` from yesterday, but today it seems like the branch is gone, and `main` is knackered with merge conflicts, so I can't rebase on main.

**Comment by MeerKatDev** [comment]
Hi, sorry, I just finished merging

**Comment by arg0d** [comment]
Which branch should this be rebased on?

**Comment by arg0d** [comment]
What I meant before is, this repo has conflicts comitted into the main branch.

**Comment by MeerKatDev** [comment]
@arg0d Yes, I'm fixing them. Sorry for the inconvenient.

**Comment by MeerKatDev** [comment]
@arg0d you should be good to go

**Comment by arg0d** [comment]
I think this is ready for review

**Pull request closed without merging**
